package hueHarmony.web.model.enums;

public enum OrderStatus {
    CREATED,
    PENDING,
    CONFIRMED,
    DELIVERED,
    COMPLETED,
    RESCHEDULED,
    NO_ANSWER,
    CANCELED,
    PARTIALLY_STOCK_AVAILABLE,
    STOCK_AVAILABLE,
    NEED_TO_IMPORT,
    DELIVER_RETURN,
//    DELIVER_RESCHEDULED,
    DELIVER_OUT_FOR_DELIVERY,
    DELIVER_CANCELED,
//    CUSTOMER_CANCELED,
    DELIVERY_RESCHEDULED,
    SHIPPED,
    ITEM_LOST,
    APPROVED
}
